name: Build and Sign App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - name: Retrieve the secret and decode it to a file
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
        run: echo $KEYSTORE_B64 | base64 --decode > $GITHUB_WORKSPACE/signing-key.jks

      - shell: bash
        env:
          GRADLEW_DIR: ${{ secrets.gradlew_dir }}
          KEYSTORE_PASSWORD: ${{ secrets.keystore_password }}
          KEY_ALIAS: ${{ secrets.key_alias }}
          KEY_PASSWORD: ${{ secrets.key_password }}
        working-directory: GRADLEW_DIR
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks \
            -Pandroid.injected.signing.store.password=KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=KEY_ALIAS \
            -Pandroid.injected.signing.key.password=KEY_PASSWORD

      - run: rm $GITHUB_WORKSPACE/signing-key.jks
        shell: bash
      
      - name: Upload apk as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: app/build/outputs/apk/release/app-release.apk
